// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action Datei;
    
    private Gtk.Action Aktionen;
    
    private Gtk.Action Hilfe;
    
    private Gtk.Action Revert;
    
    private Gtk.Action LA;
    
    private Gtk.Action SLA;
    
    private Gtk.Action Beobachten;
    
    private Gtk.Action VHinweis;
    
    private Gtk.Action home;
    
    private Gtk.Action spellCheck;
    
    private Gtk.Action quit;
    
    private Gtk.Action dialogQuestion;
    
    private Gtk.Action Beenden;
    
    private Gtk.Action LA1;
    
    private Gtk.Action SLA1;
    
    private Gtk.Action Vandal;
    
    private Gtk.Action ber;
    
    private Gtk.Action Artikel;
    
    private Gtk.Action LokalSpeichern;
    
    private Gtk.Action OnlineSpeichern;
    
    private Gtk.Action Aktualisieren;
    
    private Gtk.Action Bearbeiten;
    
    private Gtk.Action Einstellungen;
    
    private Gtk.VBox main_vbox;
    
    private Gtk.MenuBar menubar;
    
    private Gtk.VBox browserbox;
    
    private Gtk.Toolbar geckotoolbar;
    
    private Gtk.HBox navigationbox;
    
    private Gtk.Button back;
    
    private Gtk.Button forward;
    
    private Gtk.Entry urlentry;
    
    private Gtk.Button go;
    
    private Gtk.Notebook notebook2;
    
    private Gtk.ScrolledWindow scrolledwindow2;
    
    private Gtk.VPaned vpaned1;
    
    private Gtk.HBox hbox5;
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.Frame frame5;
    
    private Gtk.Alignment GtkAlignment5;
    
    private Gtk.Image image44;
    
    private Gtk.Label GtkLabel10;
    
    private Gtk.Notebook notebook1;
    
    private Gtk.ScrolledWindow scrolledwindow1;
    
    private Gtk.TreeView whitelistview;
    
    private Gtk.Label whitelist_label;
    
    private Gtk.ScrolledWindow scrolledwindow4;
    
    private Gtk.TreeView blacklistview;
    
    private Gtk.Label blacklist_label;
    
    private Gtk.ScrolledWindow scrolledwindow5;
    
    private Gtk.TreeView watchlistview;
    
    private Gtk.Label watchlist_label;
    
    private Gtk.ScrolledWindow scrolledwindow3;
    
    private Gtk.TreeView rc_view;
    
    private Gtk.Label label7;
    
    private Gtk.Alignment geckobox;
    
    private Gtk.Label label1;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar2;
    
    private Gtk.Toolbar toolbar1;
    
    private Gtk.ScrolledWindow scrolledwindow6;
    
    private Gtk.TextView textview1;
    
    private Gtk.Label artikellabel;
    
    private Gtk.TreeView treeview1;
    
    private Gtk.Label label2;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Frame frame4;
    
    private Gtk.Alignment GtkAlignment4;
    
    private Gtk.TreeView treeview5;
    
    private Gtk.Label GtkLabel9;
    
    private Gtk.Frame frame3;
    
    private Gtk.Alignment GtkAlignment3;
    
    private Gtk.TreeView treeview4;
    
    private Gtk.Label GtkLabel11;
    
    private Gtk.Label label3;
    
    private Gtk.Label label4;
    
    private Gtk.Statusbar statusbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.Datei = new Gtk.Action("Datei", Mono.Unix.Catalog.GetString("_Datei"), null, null);
        this.Datei.ShortLabel = Mono.Unix.Catalog.GetString("_Datei");
        w2.Add(this.Datei, null);
        this.Aktionen = new Gtk.Action("Aktionen", Mono.Unix.Catalog.GetString("_Aktionen"), null, null);
        this.Aktionen.ShortLabel = Mono.Unix.Catalog.GetString("_Aktionen");
        w2.Add(this.Aktionen, null);
        this.Hilfe = new Gtk.Action("Hilfe", Mono.Unix.Catalog.GetString("_Hilfe"), null, null);
        this.Hilfe.ShortLabel = Mono.Unix.Catalog.GetString("_Hilfe");
        w2.Add(this.Hilfe, null);
        this.Revert = new Gtk.Action("Revert", Mono.Unix.Catalog.GetString("_Revert"), null, "gtk-undo");
        this.Revert.ShortLabel = Mono.Unix.Catalog.GetString("_Revert");
        w2.Add(this.Revert, null);
        this.LA = new Gtk.Action("LA", Mono.Unix.Catalog.GetString("_LA"), null, "gtk-delete");
        this.LA.ShortLabel = Mono.Unix.Catalog.GetString("_LA");
        w2.Add(this.LA, null);
        this.SLA = new Gtk.Action("SLA", Mono.Unix.Catalog.GetString("_SLA"), null, "gtk-delete");
        this.SLA.ShortLabel = Mono.Unix.Catalog.GetString("_SLA");
        w2.Add(this.SLA, null);
        this.Beobachten = new Gtk.Action("Beobachten", Mono.Unix.Catalog.GetString("_Beobachten"), null, "gtk-find");
        this.Beobachten.ShortLabel = Mono.Unix.Catalog.GetString("_Beobachten");
        w2.Add(this.Beobachten, null);
        this.VHinweis = new Gtk.Action("VHinweis", Mono.Unix.Catalog.GetString("_VHinweis"), null, "gtk-dialog-error");
        this.VHinweis.ShortLabel = Mono.Unix.Catalog.GetString("_VHinweis");
        w2.Add(this.VHinweis, null);
        this.home = new Gtk.Action("home", null, null, "gtk-home");
        w2.Add(this.home, null);
        this.spellCheck = new Gtk.Action("spellCheck", null, null, "gtk-spell-check");
        w2.Add(this.spellCheck, null);
        this.quit = new Gtk.Action("quit", null, null, "gtk-quit");
        w2.Add(this.quit, null);
        this.dialogQuestion = new Gtk.Action("dialogQuestion", null, null, "gtk-dialog-question");
        w2.Add(this.dialogQuestion, null);
        this.Beenden = new Gtk.Action("Beenden", Mono.Unix.Catalog.GetString("Beenden"), null, null);
        this.Beenden.ShortLabel = Mono.Unix.Catalog.GetString("Beenden");
        w2.Add(this.Beenden, null);
        this.LA1 = new Gtk.Action("LA1", Mono.Unix.Catalog.GetString("LA+"), null, null);
        this.LA1.ShortLabel = Mono.Unix.Catalog.GetString("LA+");
        w2.Add(this.LA1, null);
        this.SLA1 = new Gtk.Action("SLA1", Mono.Unix.Catalog.GetString("SLA+"), null, null);
        this.SLA1.ShortLabel = Mono.Unix.Catalog.GetString("SLA+");
        w2.Add(this.SLA1, null);
        this.Vandal = new Gtk.Action("Vandal", Mono.Unix.Catalog.GetString("Vandal+"), null, null);
        this.Vandal.ShortLabel = Mono.Unix.Catalog.GetString("Vandal+");
        w2.Add(this.Vandal, null);
        this.ber = new Gtk.Action("ber", Mono.Unix.Catalog.GetString("Über"), null, null);
        this.ber.ShortLabel = Mono.Unix.Catalog.GetString("Über");
        w2.Add(this.ber, null);
        this.Artikel = new Gtk.Action("Artikel", Mono.Unix.Catalog.GetString("_Artikel"), null, null);
        this.Artikel.ShortLabel = Mono.Unix.Catalog.GetString("_Artikel");
        w2.Add(this.Artikel, null);
        this.LokalSpeichern = new Gtk.Action("LokalSpeichern", Mono.Unix.Catalog.GetString("_Lokal Speichern"), null, "gtk-save");
        this.LokalSpeichern.ShortLabel = Mono.Unix.Catalog.GetString("_Lokal Speichern");
        w2.Add(this.LokalSpeichern, null);
        this.OnlineSpeichern = new Gtk.Action("OnlineSpeichern", Mono.Unix.Catalog.GetString("_Online Speichern"), null, "gtk-network");
        this.OnlineSpeichern.ShortLabel = Mono.Unix.Catalog.GetString("_Online Speichern");
        w2.Add(this.OnlineSpeichern, null);
        this.Aktualisieren = new Gtk.Action("Aktualisieren", Mono.Unix.Catalog.GetString("_Aktualisieren"), null, "gtk-refresh");
        this.Aktualisieren.ShortLabel = Mono.Unix.Catalog.GetString("_Aktualisieren");
        w2.Add(this.Aktualisieren, null);
        this.Bearbeiten = new Gtk.Action("Bearbeiten", Mono.Unix.Catalog.GetString("_Bearbeiten"), null, null);
        this.Bearbeiten.ShortLabel = Mono.Unix.Catalog.GetString("_Bearbeiten");
        w2.Add(this.Bearbeiten, null);
        this.Einstellungen = new Gtk.Action("Einstellungen", Mono.Unix.Catalog.GetString("_Einstellungen"), null, null);
        this.Einstellungen.ShortLabel = Mono.Unix.Catalog.GetString("_Einstellungen");
        w2.Add(this.Einstellungen, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.CanFocus = false;
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Wikifighter");
        this.Icon = Gtk.IconTheme.Default.LoadIcon("stock_smiley-18", 16, 0);
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.main_vbox = new Gtk.VBox();
        this.main_vbox.CanFocus = false;
        this.main_vbox.Name = "main_vbox";
        // Container child main_vbox.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar'><menu action='Datei'><menuitem action='Beenden'/></menu><menu action='Bearbeiten'><menuitem action='Einstellungen'/></menu><menu action='Aktionen'><menuitem action='LA1'/><menuitem action='SLA1'/><menuitem action='Vandal'/></menu><menu action='Hilfe'><menuitem action='ber'/></menu></menubar></ui>");
        this.menubar = ((Gtk.MenuBar)(w1.GetWidget("/menubar")));
        this.menubar.CanFocus = false;
        this.menubar.Name = "menubar";
        this.main_vbox.Add(this.menubar);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.main_vbox[this.menubar]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child main_vbox.Gtk.Box+BoxChild
        this.browserbox = new Gtk.VBox();
        this.browserbox.CanFocus = false;
        this.browserbox.Name = "browserbox";
        // Container child browserbox.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><toolbar name='geckotoolbar'><toolitem action='Revert'/><toolitem action='SLA'/><toolitem action='Beobachten'/><toolitem action='VHinweis'/><toolitem action='spellCheck'/><toolitem action='dialogQuestion'/><toolitem action='home'/><toolitem action='quit'/></toolbar></ui>");
        this.geckotoolbar = ((Gtk.Toolbar)(w1.GetWidget("/geckotoolbar")));
        this.geckotoolbar.CanFocus = false;
        this.geckotoolbar.Name = "geckotoolbar";
        this.geckotoolbar.ShowArrow = false;
        this.geckotoolbar.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.geckotoolbar.IconSize = ((Gtk.IconSize)(3));
        this.browserbox.Add(this.geckotoolbar);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.browserbox[this.geckotoolbar]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child browserbox.Gtk.Box+BoxChild
        this.navigationbox = new Gtk.HBox();
        this.navigationbox.CanFocus = false;
        this.navigationbox.Name = "navigationbox";
        this.navigationbox.Spacing = 3;
        this.navigationbox.BorderWidth = ((uint)(1));
        // Container child navigationbox.Gtk.Box+BoxChild
        this.back = new Gtk.Button();
        this.back.Name = "back";
        this.back.UseStock = true;
        this.back.UseUnderline = true;
        this.back.Label = "gtk-go-back";
        this.navigationbox.Add(this.back);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.navigationbox[this.back]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child navigationbox.Gtk.Box+BoxChild
        this.forward = new Gtk.Button();
        this.forward.Name = "forward";
        this.forward.UseStock = true;
        this.forward.UseUnderline = true;
        this.forward.Label = "gtk-go-forward";
        this.navigationbox.Add(this.forward);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.navigationbox[this.forward]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child navigationbox.Gtk.Box+BoxChild
        this.urlentry = new Gtk.Entry();
        this.urlentry.Name = "urlentry";
        this.urlentry.IsEditable = true;
        this.navigationbox.Add(this.urlentry);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.navigationbox[this.urlentry]));
        w7.Position = 2;
        // Container child navigationbox.Gtk.Box+BoxChild
        this.go = new Gtk.Button();
        this.go.Name = "go";
        this.go.UseUnderline = true;
        // Container child go.Gtk.Container+ContainerChild
        Gtk.Alignment w8 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w8.CanFocus = false;
        w8.Name = "GtkAlignment2";
        // Container child GtkAlignment2.Gtk.Container+ContainerChild
        Gtk.HBox w9 = new Gtk.HBox();
        w9.CanFocus = false;
        w9.Name = "GtkHBox2";
        w9.Spacing = 2;
        // Container child GtkHBox2.Gtk.Container+ContainerChild
        Gtk.Image w10 = new Gtk.Image();
        w10.CanFocus = false;
        w10.Name = "image11";
        w10.Pixbuf = Gtk.IconTheme.Default.LoadIcon("gtk-apply", 16, 0);
        w9.Add(w10);
        // Container child GtkHBox2.Gtk.Container+ContainerChild
        Gtk.Label w12 = new Gtk.Label();
        w12.CanFocus = false;
        w12.Name = "GtkLabel3";
        w12.LabelProp = Mono.Unix.Catalog.GetString("_Go!");
        w12.UseUnderline = true;
        w9.Add(w12);
        w8.Add(w9);
        this.go.Add(w8);
        this.navigationbox.Add(this.go);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.navigationbox[this.go]));
        w16.Position = 3;
        w16.Expand = false;
        w16.Fill = false;
        this.browserbox.Add(this.navigationbox);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.browserbox[this.navigationbox]));
        w17.Position = 1;
        w17.Expand = false;
        w17.Fill = false;
        // Container child browserbox.Gtk.Box+BoxChild
        this.notebook2 = new Gtk.Notebook();
        this.notebook2.Name = "notebook2";
        // Container child notebook2.Gtk.Notebook+NotebookChild
        this.scrolledwindow2 = new Gtk.ScrolledWindow();
        this.scrolledwindow2.Name = "scrolledwindow2";
        this.scrolledwindow2.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow2.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        // Container child scrolledwindow2.Gtk.Container+ContainerChild
        Gtk.Viewport w18 = new Gtk.Viewport();
        w18.CanFocus = false;
        w18.Name = "GtkViewport";
        w18.ShadowType = ((Gtk.ShadowType)(0));
        // Container child GtkViewport.Gtk.Container+ContainerChild
        this.vpaned1 = new Gtk.VPaned();
        this.vpaned1.Name = "vpaned1";
        this.vpaned1.Position = 119;
        // Container child vpaned1.Gtk.Paned+PanedChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.CanFocus = false;
        this.hbox5.Name = "hbox5";
        // Container child hbox5.Gtk.Box+BoxChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 287;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.frame5 = new Gtk.Frame();
        this.frame5.CanFocus = false;
        this.frame5.Name = "frame5";
        this.frame5.ShadowType = ((Gtk.ShadowType)(0));
        this.frame5.LabelXalign = 0F;
        // Container child frame5.Gtk.Container+ContainerChild
        this.GtkAlignment5 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment5.CanFocus = false;
        this.GtkAlignment5.Name = "GtkAlignment5";
        this.GtkAlignment5.LeftPadding = ((uint)(12));
        // Container child GtkAlignment5.Gtk.Container+ContainerChild
        this.image44 = new Gtk.Image();
        this.image44.CanFocus = false;
        this.image44.Name = "image44";
        this.GtkAlignment5.Add(this.image44);
        this.frame5.Add(this.GtkAlignment5);
        this.GtkLabel10 = new Gtk.Label();
        this.GtkLabel10.CanFocus = false;
        this.GtkLabel10.Events = ((Gdk.EventMask)(256));
        this.GtkLabel10.Name = "GtkLabel10";
        this.GtkLabel10.LabelProp = Mono.Unix.Catalog.GetString("<b>RC-Status</b>");
        this.GtkLabel10.UseMarkup = true;
        this.frame5.LabelWidget = this.GtkLabel10;
        this.hpaned1.Add(this.frame5);
        Gtk.Paned.PanedChild w21 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.frame5]));
        w21.Resize = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.notebook1 = new Gtk.Notebook();
        this.notebook1.Name = "notebook1";
        this.notebook1.TabPos = ((Gtk.PositionType)(1));
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.scrolledwindow1 = new Gtk.ScrolledWindow();
        this.scrolledwindow1.Name = "scrolledwindow1";
        this.scrolledwindow1.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow1.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        // Container child scrolledwindow1.Gtk.Container+ContainerChild
        this.whitelistview = new Gtk.TreeView();
        this.whitelistview.Name = "whitelistview";
        this.scrolledwindow1.Add(this.whitelistview);
        this.notebook1.Add(this.scrolledwindow1);
        Gtk.Notebook.NotebookChild w23 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.scrolledwindow1]));
        w23.TabExpand = false;
        // Notebook tab
        this.whitelist_label = new Gtk.Label();
        this.whitelist_label.CanFocus = false;
        this.whitelist_label.Name = "whitelist_label";
        this.whitelist_label.LabelProp = Mono.Unix.Catalog.GetString("Whitelist");
        this.notebook1.SetTabLabel(this.scrolledwindow1, this.whitelist_label);
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.scrolledwindow4 = new Gtk.ScrolledWindow();
        this.scrolledwindow4.Name = "scrolledwindow4";
        this.scrolledwindow4.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow4.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        // Container child scrolledwindow4.Gtk.Container+ContainerChild
        this.blacklistview = new Gtk.TreeView();
        this.blacklistview.Name = "blacklistview";
        this.scrolledwindow4.Add(this.blacklistview);
        this.notebook1.Add(this.scrolledwindow4);
        Gtk.Notebook.NotebookChild w25 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.scrolledwindow4]));
        w25.Position = 1;
        w25.TabExpand = false;
        // Notebook tab
        this.blacklist_label = new Gtk.Label();
        this.blacklist_label.CanFocus = false;
        this.blacklist_label.Name = "blacklist_label";
        this.blacklist_label.LabelProp = Mono.Unix.Catalog.GetString("Blacklist");
        this.notebook1.SetTabLabel(this.scrolledwindow4, this.blacklist_label);
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.scrolledwindow5 = new Gtk.ScrolledWindow();
        this.scrolledwindow5.Name = "scrolledwindow5";
        this.scrolledwindow5.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow5.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        // Container child scrolledwindow5.Gtk.Container+ContainerChild
        this.watchlistview = new Gtk.TreeView();
        this.watchlistview.Name = "watchlistview";
        this.scrolledwindow5.Add(this.watchlistview);
        this.notebook1.Add(this.scrolledwindow5);
        Gtk.Notebook.NotebookChild w27 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.scrolledwindow5]));
        w27.Position = 2;
        w27.TabExpand = false;
        // Notebook tab
        this.watchlist_label = new Gtk.Label();
        this.watchlist_label.CanFocus = false;
        this.watchlist_label.Name = "watchlist_label";
        this.watchlist_label.LabelProp = Mono.Unix.Catalog.GetString("Beobacht-\nungsliste");
        this.notebook1.SetTabLabel(this.scrolledwindow5, this.watchlist_label);
        this.hpaned1.Add(this.notebook1);
        this.hbox5.Add(this.hpaned1);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.hbox5[this.hpaned1]));
        w29.Position = 0;
        this.vpaned1.Add(this.hbox5);
        Gtk.Paned.PanedChild w30 = ((Gtk.Paned.PanedChild)(this.vpaned1[this.hbox5]));
        w30.Resize = false;
        // Container child vpaned1.Gtk.Paned+PanedChild
        this.scrolledwindow3 = new Gtk.ScrolledWindow();
        this.scrolledwindow3.Name = "scrolledwindow3";
        this.scrolledwindow3.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow3.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        // Container child scrolledwindow3.Gtk.Container+ContainerChild
        this.rc_view = new Gtk.TreeView();
        this.rc_view.Name = "rc_view";
        this.scrolledwindow3.Add(this.rc_view);
        this.vpaned1.Add(this.scrolledwindow3);
        w18.Add(this.vpaned1);
        this.scrolledwindow2.Add(w18);
        this.notebook2.Add(this.scrolledwindow2);
        Gtk.Notebook.NotebookChild w35 = ((Gtk.Notebook.NotebookChild)(this.notebook2[this.scrolledwindow2]));
        w35.TabExpand = false;
        // Notebook tab
        this.label7 = new Gtk.Label();
        this.label7.CanFocus = false;
        this.label7.Name = "label7";
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Letzte Änderungen");
        this.notebook2.SetTabLabel(this.scrolledwindow2, this.label7);
        // Container child notebook2.Gtk.Notebook+NotebookChild
        this.geckobox = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.geckobox.CanFocus = false;
        this.geckobox.Name = "geckobox";
        this.notebook2.Add(this.geckobox);
        Gtk.Notebook.NotebookChild w36 = ((Gtk.Notebook.NotebookChild)(this.notebook2[this.geckobox]));
        w36.Position = 1;
        w36.TabExpand = false;
        // Notebook tab
        this.label1 = new Gtk.Label();
        this.label1.CanFocus = false;
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Browser");
        this.notebook2.SetTabLabel(this.geckobox, this.label1);
        // Container child notebook2.Gtk.Notebook+NotebookChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.CanFocus = false;
        this.vbox1.Name = "vbox1";
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar2'><menu action='Artikel'><menuitem action='LokalSpeichern'/><menuitem action='OnlineSpeichern'/><menuitem action='Aktualisieren'/></menu></menubar></ui>");
        this.menubar2 = ((Gtk.MenuBar)(w1.GetWidget("/menubar2")));
        this.menubar2.CanFocus = false;
        this.menubar2.Name = "menubar2";
        this.vbox1.Add(this.menubar2);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
        w37.Position = 0;
        w37.Expand = false;
        w37.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><toolbar name='toolbar1'/></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
        this.toolbar1.CanFocus = false;
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.toolbar1.IconSize = ((Gtk.IconSize)(3));
        this.vbox1.Add(this.toolbar1);
        Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
        w38.Position = 1;
        w38.Expand = false;
        w38.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.scrolledwindow6 = new Gtk.ScrolledWindow();
        this.scrolledwindow6.Name = "scrolledwindow6";
        this.scrolledwindow6.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow6.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow6.ShadowType = ((Gtk.ShadowType)(2));
        // Container child scrolledwindow6.Gtk.Container+ContainerChild
        this.textview1 = new Gtk.TextView();
        this.textview1.Name = "textview1";
        this.textview1.WrapMode = ((Gtk.WrapMode)(3));
        this.scrolledwindow6.Add(this.textview1);
        this.vbox1.Add(this.scrolledwindow6);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow6]));
        w40.Position = 2;
        this.notebook2.Add(this.vbox1);
        Gtk.Notebook.NotebookChild w41 = ((Gtk.Notebook.NotebookChild)(this.notebook2[this.vbox1]));
        w41.Position = 2;
        w41.TabExpand = false;
        // Notebook tab
        this.artikellabel = new Gtk.Label();
        this.artikellabel.CanFocus = false;
        this.artikellabel.Name = "artikellabel";
        this.artikellabel.LabelProp = Mono.Unix.Catalog.GetString("Artikeleditor");
        this.notebook2.SetTabLabel(this.vbox1, this.artikellabel);
        // Container child notebook2.Gtk.Notebook+NotebookChild
        this.treeview1 = new Gtk.TreeView();
        this.treeview1.Name = "treeview1";
        this.notebook2.Add(this.treeview1);
        Gtk.Notebook.NotebookChild w42 = ((Gtk.Notebook.NotebookChild)(this.notebook2[this.treeview1]));
        w42.Position = 3;
        w42.TabExpand = false;
        // Notebook tab
        this.label2 = new Gtk.Label();
        this.label2.CanFocus = false;
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("History");
        this.notebook2.SetTabLabel(this.treeview1, this.label2);
        // Container child notebook2.Gtk.Notebook+NotebookChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.CanFocus = false;
        this.hbox3.Name = "hbox3";
        // Container child hbox3.Gtk.Box+BoxChild
        this.frame4 = new Gtk.Frame();
        this.frame4.CanFocus = false;
        this.frame4.Name = "frame4";
        this.frame4.ShadowType = ((Gtk.ShadowType)(0));
        this.frame4.LabelXalign = 0F;
        // Container child frame4.Gtk.Container+ContainerChild
        this.GtkAlignment4 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment4.CanFocus = false;
        this.GtkAlignment4.Name = "GtkAlignment4";
        this.GtkAlignment4.LeftPadding = ((uint)(12));
        // Container child GtkAlignment4.Gtk.Container+ContainerChild
        this.treeview5 = new Gtk.TreeView();
        this.treeview5.Name = "treeview5";
        this.GtkAlignment4.Add(this.treeview5);
        this.frame4.Add(this.GtkAlignment4);
        this.GtkLabel9 = new Gtk.Label();
        this.GtkLabel9.CanFocus = false;
        this.GtkLabel9.Events = ((Gdk.EventMask)(256));
        this.GtkLabel9.Name = "GtkLabel9";
        this.GtkLabel9.LabelProp = Mono.Unix.Catalog.GetString("<b>frame4</b>");
        this.GtkLabel9.UseMarkup = true;
        this.frame4.LabelWidget = this.GtkLabel9;
        this.hbox3.Add(this.frame4);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.hbox3[this.frame4]));
        w45.Position = 0;
        w45.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.frame3 = new Gtk.Frame();
        this.frame3.CanFocus = false;
        this.frame3.Name = "frame3";
        this.frame3.ShadowType = ((Gtk.ShadowType)(0));
        this.frame3.LabelXalign = 0F;
        // Container child frame3.Gtk.Container+ContainerChild
        this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment3.CanFocus = false;
        this.GtkAlignment3.Name = "GtkAlignment3";
        this.GtkAlignment3.LeftPadding = ((uint)(12));
        // Container child GtkAlignment3.Gtk.Container+ContainerChild
        this.treeview4 = new Gtk.TreeView();
        this.treeview4.Name = "treeview4";
        this.GtkAlignment3.Add(this.treeview4);
        this.frame3.Add(this.GtkAlignment3);
        this.GtkLabel11 = new Gtk.Label();
        this.GtkLabel11.CanFocus = false;
        this.GtkLabel11.Events = ((Gdk.EventMask)(256));
        this.GtkLabel11.Name = "GtkLabel11";
        this.GtkLabel11.LabelProp = Mono.Unix.Catalog.GetString("<b>frame3</b>");
        this.GtkLabel11.UseMarkup = true;
        this.frame3.LabelWidget = this.GtkLabel11;
        this.hbox3.Add(this.frame3);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.hbox3[this.frame3]));
        w48.Position = 1;
        w48.Expand = false;
        w48.Fill = false;
        this.notebook2.Add(this.hbox3);
        Gtk.Notebook.NotebookChild w49 = ((Gtk.Notebook.NotebookChild)(this.notebook2[this.hbox3]));
        w49.Position = 4;
        w49.TabExpand = false;
        // Notebook tab
        this.label3 = new Gtk.Label();
        this.label3.CanFocus = false;
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Diff");
        this.notebook2.SetTabLabel(this.hbox3, this.label3);
        // Notebook tab
        Gtk.Label w50 = new Gtk.Label();
        w50.Visible = true;
        this.notebook2.Add(w50);
        this.label4 = new Gtk.Label();
        this.label4.CanFocus = false;
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Benutzer");
        this.notebook2.SetTabLabel(w50, this.label4);
        this.browserbox.Add(this.notebook2);
        Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.browserbox[this.notebook2]));
        w51.Position = 2;
        this.main_vbox.Add(this.browserbox);
        Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.main_vbox[this.browserbox]));
        w52.Position = 1;
        // Container child main_vbox.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.CanFocus = false;
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 2;
        this.main_vbox.Add(this.statusbar1);
        Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(this.main_vbox[this.statusbar1]));
        w53.PackType = ((Gtk.PackType)(1));
        w53.Position = 2;
        w53.Expand = false;
        w53.Fill = false;
        this.Add(this.main_vbox);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 662;
        this.DefaultHeight = 653;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.Beenden.Activated += new System.EventHandler(this.onBeenden);
        this.Einstellungen.Activated += new System.EventHandler(this.OnEinstellungenActivated);
        this.urlentry.EditingDone += new System.EventHandler(this.OnEditingDone);
        this.urlentry.KeyReleaseEvent += new Gtk.KeyReleaseEventHandler(this.OnUrlentryKeyReleaseEvent);
        this.go.Clicked += new System.EventHandler(this.OnGoClicked);
    }
}
